### ISSUE TITLE
proteus/worker start failed

### ISSUE THREAD

**Issue by wr00t** [pry0cc/proteus#2]
While run `sudo docker compose up`, I got this:
```
proteus-worker-1  | python3: can't open file '/app/bin/worker/worker.py': [Errno 2] No such file or directory
```
and I'm confused, the path of `docker-compose.yml` file is `proteus/docker-compose.yml`, why "Navigate to the bin directory and inspect the docker-compose.yml"?

**Comment by 0xtavian** [comment]
```
services:
  redis:
    image: redis
  mongo:
    image: mongo
  worker:
    image: proteus/worker
    build:
      context: bin/worker/
    volumes:
      - /home/op/.axiom/accounts/personal.json:/root/.axiom/accounts/default.json # map your account here 
      - /home/op/.axiom/modules:/root/.axiom/modules # map modules
      - /home/op/.ssh:/root/.ssh # map SSH
      - /home/op/.proteus:/app # map proteus folder to the app (for persistence of data like rawdata & scans), not 100% necessary but nice to have.
```

Under volumes, change the `/home/op/` to whatever your home directory is and it should work. @wr00t. I'll clarify the readme.
